line_length: 280
identifier_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - ID
    - id
    - URL
    - GlobalAPIKey
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
